# Uncomment the following lines to enable the Corne RGB Underglow
# CONFIG_ZMK_RGB_UNDERGLOW=y
# CONFIG_WS2812_STRIP=y

# Uncomment the following line to enable the Corne OLED Display
CONFIG_ZMK_DISPLAY=y

CONFIG_ZMK_SLEEP=y
CONFIG_ZMK_BACKLIGHT_AUTO_OFF_IDLE=y
CONFIG_ZMK_BATTERY_REPORTING=y
CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_PROXY=y
CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_FETCHING=y
CONFIG_ZMK_BLE_EXPERIMENTAL_CONN=y
CONFIG_ZMK_BLE_EXPERIMENTAL_FEATURES=y
CONFIG_ZMK_WIDGET_LAYER_STATUS=y
CONFIG_ZMK_WIDGET_BATTERY_STATUS=y
CONFIG_ZMK_WIDGET_BATTERY_STATUS_SHOW_PERCENTAGE=y
CONFIG_ZMK_WIDGET_OUTPUT_STATUS=y
CONFIG_ZMK_WIDGET_WPM_STATUS=y
CONFIG_EC11=y
CONFIG_ZMK_KEYBOARD_NAME=Gabe's Corne
CONFIG_ZMK_WPM=y
CONFIG_BT=y
CONFIG_ZMK_BLE=y
CONFIG_ZMK_BLE_PASSKEY_ENTRY=y
CONFIG_ZMK_SPLIT=y
CONFIG_ZMK_BACKLIGHT=y
CONFIG_ZMK_SPLIT && ZMK_SPLIT_ROLE_CENTRAL=y
CONFIG_ZMK_SPLIT_ROLE_CENTRAL=y
CONFIG_ZMK_BACKLIGHT=y
CONFIG_EC11_TRIGGER_GLOBAL_THREAD=1
sensor-bindings = <&inc_dec_kp PG_UP PG_DN>;
